
import ProjectExceptions.ToFewPointsToMakePlygon;
import java.awt.geom.Point2D;
import java.util.ArrayList;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author drapek
 */
public class MonteCarloWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MonteCarloWindow(ForwardingDataPackage forwaredPackage) {
        initComponents();
        MonteCarloWindowLogic.setForwardedData(forwaredPackage);
        monteCarloCalc = new CalculateAreaMonteCarlo(forwaredPackage.getConvexHullPoints());
        jLabelSuccessInfo.setVisible(false);
        
        MonteCarloWindowLogic.drawPointsOnChart(jPanelPointChart, forwaredPackage.getConvexHullPoints(), new ArrayList<>(), new ArrayList<>());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPointChart = new javax.swing.JPanel();
        jPanelGlobalButtons = new javax.swing.JPanel();
        jPanelAddPoints = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jButtonPreviosWindow = new javax.swing.JButton();
        jPanelAreaCounting = new javax.swing.JPanel();
        jLabelTitleHullPanel = new javax.swing.JLabel();
        jLabelRandomPointsByStep = new javax.swing.JLabel();
        jSpinnerRndNmbByStep = new javax.swing.JSpinner();
        jButtonNextStep = new javax.swing.JButton();
        jLabelNmbInnerPointsInfo = new javax.swing.JLabel();
        jLabelNmbInnerPointsValue = new javax.swing.JLabel();
        jLabelNmbOutterPointsInfo = new javax.swing.JLabel();
        jLabelNmbOutterPointsValue = new javax.swing.JLabel();
        jButtonGoToEnd = new javax.swing.JButton();
        jButtonResetMonteCarlo = new javax.swing.JButton();
        jLabelAreaInfo = new javax.swing.JLabel();
        jLabelAreaValue = new javax.swing.JLabel();
        jLabelRandomPoints = new javax.swing.JLabel();
        jSpinnerRndNmb = new javax.swing.JSpinner();
        jLabelSuccessInfo = new javax.swing.JLabel();
        jButtonStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPointChart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelPointChartLayout = new javax.swing.GroupLayout(jPanelPointChart);
        jPanelPointChart.setLayout(jPanelPointChartLayout);
        jPanelPointChartLayout.setHorizontalGroup(
            jPanelPointChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        jPanelPointChartLayout.setVerticalGroup(
            jPanelPointChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelAddPointsLayout = new javax.swing.GroupLayout(jPanelAddPoints);
        jPanelAddPoints.setLayout(jPanelAddPointsLayout);
        jPanelAddPointsLayout.setHorizontalGroup(
            jPanelAddPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jPanelAddPointsLayout.setVerticalGroup(
            jPanelAddPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButtonClose.setText("Zamknij");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonPreviosWindow.setText("Cofnij");
        jButtonPreviosWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviosWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGlobalButtonsLayout = new javax.swing.GroupLayout(jPanelGlobalButtons);
        jPanelGlobalButtons.setLayout(jPanelGlobalButtonsLayout);
        jPanelGlobalButtonsLayout.setHorizontalGroup(
            jPanelGlobalButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGlobalButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelGlobalButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGlobalButtonsLayout.createSequentialGroup()
                        .addComponent(jPanelAddPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGlobalButtonsLayout.createSequentialGroup()
                        .addComponent(jButtonPreviosWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClose)
                        .addGap(43, 43, 43))))
        );
        jPanelGlobalButtonsLayout.setVerticalGroup(
            jPanelGlobalButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGlobalButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddPoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addGroup(jPanelGlobalButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonPreviosWindow))
                .addContainerGap())
        );

        jPanelAreaCounting.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTitleHullPanel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitleHullPanel.setText("Obliczanie pola metodą Monte Carlo");

        jLabelRandomPointsByStep.setText("Ilość randomowych pkt w kroku: ");

        jSpinnerRndNmbByStep.setValue(100);

        jButtonNextStep.setText("Kolejny krok");
        jButtonNextStep.setEnabled(false);
        jButtonNextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextStepActionPerformed(evt);
            }
        });

        jLabelNmbInnerPointsInfo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabelNmbInnerPointsInfo.setForeground(new java.awt.Color(0, 153, 0));
        jLabelNmbInnerPointsInfo.setText("Ilość pkt wewnątrz otoczki: ");

        jLabelNmbInnerPointsValue.setText("0");

        jLabelNmbOutterPointsInfo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabelNmbOutterPointsInfo.setForeground(new java.awt.Color(204, 0, 0));
        jLabelNmbOutterPointsInfo.setText("Ilość pkt na zewnątrz otoczki: ");

        jLabelNmbOutterPointsValue.setText("0");

        jButtonGoToEnd.setText("Idź do końca");
        jButtonGoToEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoToEndActionPerformed(evt);
            }
        });

        jButtonResetMonteCarlo.setText("Zresetuj obliczanie pola");
        jButtonResetMonteCarlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetMonteCarloActionPerformed(evt);
            }
        });

        jLabelAreaInfo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabelAreaInfo.setText("Pole obliczonej figury: ");

        jLabelAreaValue.setText("0");

        jLabelRandomPoints.setText("Ilość wyszystkich punktów: ");

        jSpinnerRndNmb.setValue(1000);

        jLabelSuccessInfo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelSuccessInfo.setForeground(new java.awt.Color(0, 204, 0));
        jLabelSuccessInfo.setText("Zakończono!");
        jLabelSuccessInfo.setToolTipText("");

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAreaCountingLayout = new javax.swing.GroupLayout(jPanelAreaCounting);
        jPanelAreaCounting.setLayout(jPanelAreaCountingLayout);
        jPanelAreaCountingLayout.setHorizontalGroup(
            jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAreaCountingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitleHullPanel)
                .addGap(55, 55, 55))
            .addGroup(jPanelAreaCountingLayout.createSequentialGroup()
                .addGroup(jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAreaCountingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelAreaCountingLayout.createSequentialGroup()
                                    .addComponent(jLabelNmbInnerPointsInfo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNmbInnerPointsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelAreaValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelAreaCountingLayout.createSequentialGroup()
                                    .addGroup(jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelAreaCountingLayout.createSequentialGroup()
                                            .addComponent(jLabelAreaInfo)
                                            .addGap(53, 53, 53))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAreaCountingLayout.createSequentialGroup()
                                            .addComponent(jLabelNmbOutterPointsInfo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                    .addComponent(jLabelNmbOutterPointsValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAreaCountingLayout.createSequentialGroup()
                                    .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonNextStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAreaCountingLayout.createSequentialGroup()
                                    .addComponent(jButtonGoToEnd)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonResetMonteCarlo)))
                            .addGroup(jPanelAreaCountingLayout.createSequentialGroup()
                                .addGroup(jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelRandomPoints)
                                    .addComponent(jLabelRandomPointsByStep))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinnerRndNmbByStep, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(jSpinnerRndNmb)))))
                    .addGroup(jPanelAreaCountingLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabelSuccessInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAreaCountingLayout.setVerticalGroup(
            jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAreaCountingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitleHullPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRandomPoints)
                    .addComponent(jSpinnerRndNmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRandomPointsByStep)
                    .addComponent(jSpinnerRndNmbByStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNextStep)
                    .addComponent(jButtonStart))
                .addGap(8, 8, 8)
                .addGroup(jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGoToEnd)
                    .addComponent(jButtonResetMonteCarlo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNmbInnerPointsInfo)
                    .addComponent(jLabelNmbInnerPointsValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAreaCountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNmbOutterPointsInfo)
                    .addComponent(jLabelNmbOutterPointsValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAreaInfo)
                .addGap(7, 7, 7)
                .addComponent(jLabelAreaValue)
                .addGap(38, 38, 38)
                .addComponent(jLabelSuccessInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelGlobalButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelPointChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelAreaCounting, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAreaCounting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPointChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jPanelGlobalButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextStepActionPerformed
       monteCarloCalc.setOneStepRandomSamplesNumber( (int) jSpinnerRndNmbByStep.getValue());
       if( !monteCarloCalc.oneStepInCountingArea() ) {
           actionAfterCountArea();
           return;
       }
        updateAllWindowStatistics();
        MonteCarloWindowLogic.drawPointsOnChart(jPanelPointChart, MonteCarloWindowLogic.getForwardedData().getConvexHullPoints(), 
                monteCarloCalc.getHitsArrayList(), monteCarloCalc.getMissArrayList());
       
    }//GEN-LAST:event_jButtonNextStepActionPerformed

    private void jButtonPreviosWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviosWindowActionPerformed

        FindHullWindow newWindow = new FindHullWindow(MonteCarloWindowLogic.getForwardedData());
        newWindow.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        newWindow.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonPreviosWindowActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonGoToEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoToEndActionPerformed

       monteCarloCalc.goToTheEndOfAlgoritm();
       updateAllWindowStatistics();
       MonteCarloWindowLogic.drawPointsOnChart(jPanelPointChart, MonteCarloWindowLogic.getForwardedData().getConvexHullPoints(), 
                monteCarloCalc.getHitsArrayList(), monteCarloCalc.getMissArrayList());
       actionAfterCountArea();
    }//GEN-LAST:event_jButtonGoToEndActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        jButtonNextStep.setEnabled(true);
        monteCarloCalc.setOverallNumerOfSamples((int) jSpinnerRndNmb.getValue());
        monteCarloCalc.setOneStepRandomSamplesNumber( (int) jSpinnerRndNmbByStep.getValue());
        //to make one step at first    
        jButtonNextStepActionPerformed(evt);
        jButtonStart.setEnabled(false);
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonResetMonteCarloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetMonteCarloActionPerformed
        jButtonGoToEnd.setEnabled(true);
        jButtonStart.setEnabled(true);
        jButtonNextStep.setEnabled(false);
        jLabelSuccessInfo.setVisible(false);
        monteCarloCalc = new CalculateAreaMonteCarlo(MonteCarloWindowLogic.forwardedData.getConvexHullPoints());
        updateAllWindowStatistics();
    }//GEN-LAST:event_jButtonResetMonteCarloActionPerformed
    
    private void updateAllWindowStatistics() {
        jLabelNmbInnerPointsValue.setText(monteCarloCalc.getHitsNumber() + "");
        jLabelNmbOutterPointsValue.setText(monteCarloCalc.getMissNumber() + "");
        jLabelAreaValue.setText(monteCarloCalc.getAreaAtThisMoment() + "");
        
    }
    
    private void actionAfterCountArea() {
       jButtonGoToEnd.setEnabled(false);
       jButtonNextStep.setEnabled(false);
       jButtonStart.setEnabled(false);
       jLabelSuccessInfo.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    CalculateAreaMonteCarlo monteCarloCalc;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonGoToEnd;
    private javax.swing.JButton jButtonNextStep;
    private javax.swing.JButton jButtonPreviosWindow;
    private javax.swing.JButton jButtonResetMonteCarlo;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JLabel jLabelAreaInfo;
    private javax.swing.JLabel jLabelAreaValue;
    private javax.swing.JLabel jLabelNmbInnerPointsInfo;
    private javax.swing.JLabel jLabelNmbInnerPointsValue;
    private javax.swing.JLabel jLabelNmbOutterPointsInfo;
    private javax.swing.JLabel jLabelNmbOutterPointsValue;
    private javax.swing.JLabel jLabelRandomPoints;
    private javax.swing.JLabel jLabelRandomPointsByStep;
    private javax.swing.JLabel jLabelSuccessInfo;
    private javax.swing.JLabel jLabelTitleHullPanel;
    private javax.swing.JPanel jPanelAddPoints;
    private javax.swing.JPanel jPanelAreaCounting;
    private javax.swing.JPanel jPanelGlobalButtons;
    private javax.swing.JPanel jPanelPointChart;
    private javax.swing.JSpinner jSpinnerRndNmb;
    private javax.swing.JSpinner jSpinnerRndNmbByStep;
    // End of variables declaration//GEN-END:variables
}
